In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("../per.csv")
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

deleting stop words

In [5]:
with open('stopwords.txt', encoding='utf-8') as stopwords_file:
    stopwords = stopwords_file.read().splitlines()
stopwords

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسیب پذیرند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن گاه',
 'آنان',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'اتفاقا',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احیاناً',
 'اخیر',
 'اخیراً',
 'اری',
 'از',
 'از آن پس',
 'از جمله',
 'ازاین رو',
 'ازجمله',
 'ازش',
 'اساسا',
 'اساساً',
 'است',
 'استفاد',
 'استفاده',
 'اسلامی اند',
 'اش',
 'اشتباها',
 'اشکارا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اعلام',
 'اغلب',
 'افزود',
 'افسوس',
 'اقل',
 'اقلیت',
 'الا',
 'الان',
 'البته',
 'البتّه',
 'الهی',
 'الی',
 '

In [6]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\salim\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\salim\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [7]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

1514

In [8]:
from hazm import Stemmer
stemmer = Stemmer()

In [9]:
stemmer.stem('کتاب ها')

'کتاب '

In [10]:
from hazm import Lemmatizer
lem = Lemmatizer()

In [11]:
lem.lemmatize("رفتم")

'رفت#رو'

In [12]:
from hazm import word_tokenize

In [13]:
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    title_body_tokenized_filtered_lemed = [lem.lemmatize(w).replace('#', ' ') for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_lemed) + ' ' + ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [14]:
dataset.head()

title_body category
0  وزير علوم درجمع استاد نمونه سن بازنشستگي استاد...   آموزشي
1  گردهمايي دانش‌آموختگان موسسه آموزش عالي سوره ب...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  همايش يكروزه آسيب شناسي مفهوم روابط عمومي بابل...  اجتماعي
4  وضعيت اقتصادي ميزان تحصيلات والدين مهمترين عوا...   آموزشي

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
vectorizer.fit(dataset['title_body'])

TfidfVectorizer(ngram_range=(1, 2))

In [17]:
X = vectorizer.transform(dataset['title_body'])

In [18]:
X

<10999x1858916 sparse matrix of type '<class 'numpy.float64'>'
	with 6228926 stored elements in Compressed Sparse Row format>

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [21]:
y

array([ 0,  0,  0, ..., 10, 10, 10])

In [22]:
len(y)

10999

In [23]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [24]:
np.shape(X)

(10999, 1858916)

In [25]:
np.shape(y)

(10999,)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(X, y)

ساخت مدل  با استفاده از svm

In [28]:
from sklearn import svm 

In [29]:
svmc = svm.SVC()
svmc.fit(x_train, y_train)

SVC()

In [30]:
svmc.score(x_test, y_test)

0.8403636363636363

In [31]:
from sklearn.metrics import classification_report, confusion_matrix

In [32]:
y_pred = svmc.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.89       273
           1       0.63      0.68      0.65       268
           2       0.83      0.76      0.79       250
           3       0.83      0.95      0.88       239
           4       0.88      0.89      0.88       236
           5       0.80      0.75      0.77       259
           6       0.83      0.70      0.76       241
           7       0.81      0.88      0.84       251
           8       0.90      0.88      0.89       241
           9       0.95      0.92      0.94       279
          10       0.97      0.96      0.96       213

    accuracy                           0.84      2750
   macro avg       0.84      0.84      0.84      2750
weighted avg       0.84      0.84      0.84      2750



In [33]:
print(confusion_matrix(y_test, y_pred))

[[246  11   0   2   0   2   7   3   1   0   1]
 [  9 182  14   7   3   9   8  22   4   7   3]
 [  0  35 189   4   0   7   7   3   2   2   1]
 [  0   3   1 226   0   3   6   0   0   0   0]
 [  0   7   1   0 210  10   0   5   2   1   0]
 [  3  11   8   4  17 194   3   6  12   1   0]
 [ 22   4   4  27   1   4 168   7   2   1   1]
 [  2  14   2   0   2   4   4 221   0   1   1]
 [  0  11   4   1   5   6   0   1 213   0   0]
 [  0  12   4   1   1   1   0   3   0 257   0]
 [  0   1   1   1   0   3   0   2   0   0 205]]


ساخت مدل با استفاده از XGBoost

In [34]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

In [35]:
model2 = GradientBoostingClassifier(
    n_estimators=10,
    learning_rate=0.1,
    max_depth=2,
    random_state=42,
    max_features="sqrt"
)

In [36]:
model2.fit(x_train, y_train)

GradientBoostingClassifier(max_depth=2, max_features='sqrt', n_estimators=10,
                           random_state=42)

In [37]:
y_pred2 = model2.predict(x_test)

In [38]:
accuracy_score(y_test, y_pred2)

0.3952727272727273

In [39]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.57      0.41      0.47       273
           1       0.50      0.10      0.17       268
           2       0.38      0.28      0.32       250
           3       0.61      0.87      0.72       239
           4       0.43      0.60      0.50       236
           5       0.42      0.39      0.40       259
           6       0.45      0.30      0.36       241
           7       0.75      0.18      0.29       251
           8       0.53      0.36      0.43       241
           9       0.53      0.29      0.37       279
          10       0.17      0.68      0.27       213

    accuracy                           0.40      2750
   macro avg       0.49      0.40      0.39      2750
weighted avg       0.49      0.40      0.39      2750



In [40]:
print(confusion_matrix(y_test, y_pred2))

[[111   8  15  36   7   3  10   0   2   5  76]
 [ 12  27  22  25  19  22  11   2  14  12 102]
 [  6   6  69  15  13  24  11   1  10   4  91]
 [  0   1   1 208   0  12   1   1   0   0  15]
 [  7   1   1   0 141  12   8   1  15   8  42]
 [  9   4  12   6  39 100  10   2   8  11  58]
 [ 20   1  16  25  10   8  73   2   5   4  77]
 [ 12   1  16   2  35  17  18  45   6   7  92]
 [  1   1   6   7  34  18   2   0  87  19  66]
 [ 10   4  17  14  14  12   7   2   7  81 111]
 [  7   0   8   1  16   8  10   4  11   3 145]]
